# -*- coding: utf-8 -*-
__author__ = "Sommily"
sql = """
SELECT 
      CASE X.TRADE_MKT_REF WHEN 1 THEN 'SZ' WHEN 2 THEN 'SH' END + X.STOCKCODE AS Obj,
      A.CTRL_NAME AS mc,
      B.LEG_PERSON AS frdb,
      B.REGI_CAP/10000 AS zczb,
      CONVERT(VARCHAR(10),B.BUILD_DATE,120) AS clrq,QKTZ20160429.dbo.Date2Str( B.BUILD_DATE ) AS II_clrq,
      B.PRI_BIZ AS jyyw,
      (SELECT REF_NAME FROM GEN_REF WHERE CLS_CODE=104 AND REF_CODE=B.ORG_TYPE) AS qylx
FROM STK_CODE X with(nolock)
  INNER JOIN STK_CTRL_HLD_INFO A with(nolock) ON X.COMCODE=A.COMCODE AND X.STOCKCODE='{STOCKCODE}'
    AND X.ISVALID=1 AND A.ISVALID=1
    AND A.ENDDATE=(SELECT MAX(ENDDATE) FROM STK_CTRL_HLD_INFO WHERE COMCODE=A.COMCODE)
  LEFT JOIN ORG_PROFILE B with(nolock) ON A.ORGCODE=B.OrgCode AND B.ISVALID=1"""
