# -*- coding: utf-8 -*-
__author__ = "Sommily"
sql = """SELECT
      CASE X.TRADE_MKT_REF WHEN 1 THEN 'SZ' WHEN 2 THEN 'SH' END + X.STOCKCODE AS Obj,
      CONVERT(VARCHAR(12),A.ENDDATE,112) AS 'Date',QKTZ20160429.dbo.Date2Str( A.ENDDATE ) AS II_Date,
      C.TOT_HLD AS gdrs,
      A.RANK AS xh,
      A.NAME AS gdmc,
      A.SHR_NUM/10000 AS cgs,
      case when A.HOLD_NUM = 0 then 0
           when A.HOLD_NUM is null then 0
           else ROUND(A.SHR_NUM*A.HOLD_PCT/A.HOLD_NUM,4)
           end AS zzgs,
      (ISNULL(A.SHR_NUM,0)-ISNULL(B.SHR_NUM,0))/10000 AS zjqk,
      A.SHR_CLS_NAME AS gbxz,
      A.COMCODE AS gsdm,
 	  CASE WHEN ISNULL(A.HOLD_NUM,-1)=ISNULL(B.HOLD_NUM,-1) THEN '无变动'
	     WHEN ISNULL(A.HOLD_NUM,-1)<ISNULL(B.HOLD_NUM,-1) THEN '减少'
	     WHEN A.HOLD_NUM<>0 AND ISNULL(B.HOLD_NUM,0)=0 THEN '新进'
	     WHEN ISNULL(A.HOLD_NUM,-1)>ISNULL(B.HOLD_NUM,-1) THEN '增加'
	     END AS zjsm
FROM STK_CODE X with(nolock)
  INNER JOIN STK_CIR_CLS_DTL A with(nolock) ON X.COMCODE=A.COMCODE AND X.ISVALID=1 AND A.ISVALID=1 AND X.STOCKCODE='{STOCKCODE}'
  LEFT JOIN STK_CIR_CLS_DTL B with(nolock) ON B.ISVALID=1 AND A.[NAME]=B.[NAME] AND A.COMCODE=B.COMCODE
    AND B.ENDDATE=(SELECT MAX(ENDDATE) FROM STK_CIR_CLS_DTL WHERE ISVALID=1 AND COMCODE=A.COMCODE AND ENDDATE<A.ENDDATE)
  INNER JOIN STK_HOLDER_NUM C with(nolock) ON X.COMCODE=C.COMCODE AND C.ISVALID=1 AND A.ENDDATE=C.CHANGEDATE
WHERE A.ENDDATE>=CAST(YEAR(GETDATE())-2 AS VARCHAR) +'-01-01'
ORDER BY A.ENDDATE DESC,A.RANK ASC"""
