# -*- coding: utf-8 -*-
__author__ = "Sommily"

sql = """SELECT
      CASE X.TRADE_MKT_REF WHEN 1 THEN 'SZ' WHEN 2 THEN 'SH' END + X.STOCKCODE AS Obj
    , CONVERT(VARCHAR(12),A.TRADEDATE,112) AS 'Date'
	,QKTZ20160429.dbo.Date2Str( A.TRADEDATE ) AS II_Date
    , A.WRT_PRC AS jg
    , B.TCLOSE AS drspj
    , (A.WRT_PRC/NULLIF(B.TCLOSE,0)-1)*100 AS zjl
    , A.TVOLUME AS cjl
    , A.TVALUE AS cjje
    , A.BUY_BRANCH AS mf
    , A.SELL_BRANCH AS mf2
    , cast(A.[SEQ] as varchar) as RsId
FROM STK_CODE X with(nolock)
  INNER JOIN Genius2..STK_SEC_TRADE_INFO A with(nolock) ON X.INNER_CODE=A.INNER_CODE AND X.STOCKCODE='{STOCKCODE}' AND X.ISVALID=1 AND A.ISVALID=1
  LEFT JOIN View_Stk_Mkt_gt_20140101 B with(nolock) ON X.INNER_CODE=B.INNER_CODE AND A.TRADEDATE=B.TRADEDATE
WHERE A.TRADEDATE>=CAST(YEAR(GETDATE())-2 AS VARCHAR) +'-01-01'
ORDER BY A.TRADEDATE DESC"""
