# -*- coding: utf-8 -*-
__author__ = "Sommily"
sql = """
SELECT 
      CASE X.TRADE_MKT_REF WHEN 1 THEN 'SZ' WHEN 2 THEN 'SH' END + X.STOCKCODE AS Obj,
      CONVERT(VARCHAR(12),A.ENDDATE,112) AS 'Date',QKTZ20160429.dbo.Date2Str( A.ENDDATE ) AS II_Date,
      '万元' AS dw,
      A.P110101/10000 AS yysr,
      A.P110202/10000 AS yycb,
      A.P130201/10000 AS tzsy,
      A.P130801/10000 AS yywszje,
      A.P130101/10000 AS yylr,
      A.P140101/10000 AS lrze,
      A.P150101/10000 AS jlr,
      B.B310701/10000 AS wfplr,
       CASE a.RPT_SRC WHEN '第一季度报' THEN 10
				   WHEN '中报' THEN 20
				   WHEN '第三季度报' THEN 30
				   WHEN '年报' THEN 40
				   WHEN '申报稿' THEN 50
				   WHEN '招股说明书' THEN 60
				   WHEN '上市公告书' THEN 70
				   WHEN '第一季度报' THEN 90
				   ELSE 90 END AS bgfldm --  报告分类代码
FROM STK_CODE X with(nolock)
  INNER JOIN STK_INCOME_GEN A with(nolock) ON X.COMCODE = A.COMCODE AND X.STOCKCODE = '{STOCKCODE}'  AND X.ISVALID=1
  LEFT	JOIN  STK_BALA_GEN B  with(nolock) ON  x.COMCODE=b.COMCODE   AND b.RPT_DATE=a.RPT_DATE  AND b.ENDDATE=a.ENDDATE   AND b.ISVALID=1 AND b.RPT_TYPE='合并'
WHERE A.ISVALID=1 AND A.RPT_TYPE = '合并' AND MONTH(A.STARTDATE)=1
  AND A.ENDDATE>=CAST(YEAR(GETDATE())-3 AS VARCHAR) +'-01-01'
  AND A.RPT_DATE = (SELECT MAX(RPT_DATE) FROM STK_INCOME_GEN
                    WHERE COMCODE = A.COMCODE AND ENDDATE = A.ENDDATE AND RPT_TYPE = A.RPT_TYPE AND MONTH(STARTDATE)=1)
ORDER BY A.ENDDATE DESC"""
