# -*- coding: utf-8 -*-
__author__ = "Sommily"
sql = """SELECT TOP 1
        CASE X.TRADE_MKT_REF WHEN 1 THEN 'SZ' WHEN 2 THEN 'SH' END + X.STOCKCODE AS Obj,
        ROUND(A.TOTAL/10000,4) AS zgb,
        ROUND(A.FL_SHR/10000,4) AS zltgb,
        (CASE X.STK_TYPE_REF WHEN 1 THEN A.FL_ASHR WHEN 2 THEN A.B_SHR END)/10000 AS dqltgb,
        (SELECT TOP 1 TOT_HLD AS gdrs FROM STK_HOLDER_NUM A WHERE ISVALID=1 AND COMCODE=X.COMCODE ORDER BY A.CHANGEDATE DESC)AS gdrs,
        (SELECT TOP 1 CTRL_NAME FROM STK_CTRL_HLD_INFO WHERE COMCODE=X.COMCODE ORDER BY ENDDATE DESC,HLD_NUM DESC) AS kggd,
        (SELECT TOP 1 TOT_SHR_PCT FROM STK_MAIN_HOLDER WHERE COMCODE=X.COMCODE AND ISVALID=1 AND RANK=1 ORDER BY ENDDATE DESC) AS qsdgdbl
FROM STK_CODE X with(nolock)
  INNER JOIN STK_SHR_STRU A with(nolock) ON X.COMCODE=A.COMCODE AND X.STOCKCODE='{STOCKCODE}'
    AND X.ISVALID=1 AND A.ISVALID=1
ORDER BY A.CHANGEDATE DESC"""
